name: PR Notification to Telegram
on:
    pull_request:
        types:
        - opened

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: send telegram message on PR opened
              uses: appleboy/telegram-action@master
              with:
                to: ${{ secrets.TELEGRAM_PR_CHANNEL_ID }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                message: |
                    https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
